version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.5-browsers
    working_directory: ~/laravel

    steps:
      - checkout

      - run:
         name: Update composer to latest version
         command: composer self-update

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: vendor/bin/phpunit